### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Howon** [ADI-Labs/livesubway#32]
DONE:
async load of routes
caching routes/stops using indexedDB

NEEDED:
Flatten straight lines as 2 points instead of literally hundreds 
Cache HTTP requests

**Comment by Howon** [comment]
@alexander-yu @alanhdu any thoughts?

**Comment by alexander-yu** [comment]
What do you mean by caching HTTP requests/what kind of requests would be cached? Other than that, looks good to me.

**Comment by Howon** [comment]
using geojson reduces file size by 1/7th so im playing with that rn
